name: MAIN CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar versão do Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      - name: Instalar dependências
        run: |
          brew install xcodegen
          xcodegen generate

      - name: Compilar o projeto
        run: |
          set -eo pipefail
          xcodebuild clean build \
          -project TestMELI.xcodeproj \
          -scheme TestMELI \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
          CODE_SIGNING_ALLOWED=NO

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar versão do Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      - name: Rodar testes
        run: |
          set -eo pipefail
          xcodebuild test \
          -project TestMELI.xcodeproj \
          -scheme TestMELI \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
          CODE_SIGNING_ALLOWED=NO
